CREATE DATABASE IF NOT EXISTS Screenless;
USE Screenless;

CREATE USER IF NOT EXISTS 'screenless_user'@'%' IDENTIFIED BY 'screenless';
GRANT ALL PRIVILEGES ON Screenless.* TO 'screenless_user'@'%';
FLUSH PRIVILEGES;

CREATE TABLE USUARIO (
    Id_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sobrenome VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    telefone VARCHAR(20) UNIQUE,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    xp_usuario int
);

CREATE TABLE EVENTO (
    ID_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    organizador VARCHAR(100) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    data_hora DATETIME NOT NULL,
    descricao TEXT,
    foto varchar(255),
    ID_USUARIO_CRIADOR INT,
    CONSTRAINT fk_usuario_criador
        FOREIGN KEY (ID_USUARIO_CRIADOR) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE HISTORICO_EVENTO(
    ID_HIST_EVENTO INT auto_increment PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    CONSTRAINT fk_hist_usuario
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT fk_hist_evento
        FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);

CREATE TABLE COMUNIDADE(
    ID_RELATO INT auto_increment PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    Titulo varchar(100),
    Relato varchar(300),
    Data DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_comunidade_usuario
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE DESAFIOS (
    ID_DESAFIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO int not null,
    nome_usuario VARCHAR(100) NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
    Descricao TEXT,
    XP INT NOT NULL,
    foto VARCHAR(255)
);