CREATE DATABASE IF NOT EXISTS `screenless-db`;
USE `screenless-db`;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'screenless';
GRANT ALL PRIVILEGES ON `screenless-db`.* TO 'admin'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS USUARIO (
    Id_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sobrenome VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    telefone VARCHAR(20) UNIQUE,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    xp_usuario INT
);

CREATE TABLE IF NOT EXISTS EVENTO (
    ID_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    organizador VARCHAR(100) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    data_hora DATETIME NOT NULL,
    descricao TEXT,
    foto VARCHAR(255),
    ID_USUARIO_CRIADOR INT,
    CONSTRAINT fk_usuario_criador
        FOREIGN KEY (ID_USUARIO_CRIADOR) REFERENCES USUARIO(Id_USUARIO)
);

CREATE TABLE IF NOT EXISTS HISTORICO_EVENTO (
    ID_HIST_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    CONSTRAINT fk_hist_usuario
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(Id_USUARIO),
    CONSTRAINT fk_hist_evento
        FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);

CREATE TABLE IF NOT EXISTS COMUNIDADE (
    ID_RELATO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    Titulo VARCHAR(100),
    Relato VARCHAR(300),
    Data DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_comunidade_usuario
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(Id_USUARIO)
);

CREATE TABLE IF NOT EXISTS DESAFIOS (
    ID_DESAFIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    nome_usuario VARCHAR(100) NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
    Descricao TEXT,
    XP INT NOT NULL,
    foto VARCHAR(255)
);
